// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function Chikuwa(arg1:string):Promise<string>;

export function GetVersion():Promise<string>;

export function OpenConfigDirectory():Promise<void>;

export function OpenLogDirectory():Promise<void>;

export function Post(arg1:string):Promise<string>;

export function PostAndForget(arg1:string):Promise<void>;

export function SetScheduler():Promise<void>;

export function SetXRPCClient():Promise<void>;
