// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function Chikuwa(arg1) {
  return window['go']['main']['App']['Chikuwa'](arg1);
}

export function DispatchCommand(arg1) {
  return window['go']['main']['App']['DispatchCommand'](arg1);
}

export function GetContext() {
  return window['go']['main']['App']['GetContext']();
}

export function OpenConfigDirectory() {
  return window['go']['main']['App']['OpenConfigDirectory']();
}

export function OpenLogDirectory() {
  return window['go']['main']['App']['OpenLogDirectory']();
}

export function Post(arg1) {
  return window['go']['main']['App']['Post'](arg1);
}

export function PostAndForget(arg1) {
  return window['go']['main']['App']['PostAndForget'](arg1);
}

export function SetScheduler() {
  return window['go']['main']['App']['SetScheduler']();
}

export function SetXRPCClient() {
  return window['go']['main']['App']['SetXRPCClient']();
}

export function UploadImage(arg1) {
  return window['go']['main']['App']['UploadImage'](arg1);
}
