// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function Chikuwa() {
  return window['go']['main']['App']['Chikuwa']();
}

export function Greet(arg1) {
  return window['go']['main']['App']['Greet'](arg1);
}

export function Post(arg1) {
  return window['go']['main']['App']['Post'](arg1);
}
